## Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Load Dataset

In [2]:
dataset = pd.read_csv('HR_comma_sep.csv')
X = dataset.iloc[:,[0,4,7,9]].values
Y = dataset.iloc[:,6].values

# Data Processing 

In [11]:
dataset.isnull().count()

satisfaction_level       14999
last_evaluation          14999
number_project           14999
average_montly_hours     14999
time_spend_company       14999
Work_accident            14999
left                     14999
promotion_last_5years    14999
Department               14999
salary                   14999
dtype: int64

In [8]:
dataset.isna().count()

satisfaction_level       14999
last_evaluation          14999
number_project           14999
average_montly_hours     14999
time_spend_company       14999
Work_accident            14999
left                     14999
promotion_last_5years    14999
Department               14999
salary                   14999
dtype: int64

In [12]:
dataset.count()

satisfaction_level       14999
last_evaluation          14999
number_project           14999
average_montly_hours     14999
time_spend_company       14999
Work_accident            14999
left                     14999
promotion_last_5years    14999
Department               14999
salary                   14999
dtype: int64

In [16]:
dataset['salary'].value_counts()

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [17]:
dataset['satisfaction_level'].value_counts()

0.10    358
0.11    335
0.74    257
0.77    252
0.84    247
       ... 
0.25     34
0.28     31
0.27     30
0.12     30
0.26     30
Name: satisfaction_level, Length: 92, dtype: int64

In [18]:
dataset['time_spend_company'].value_counts()

3     6443
2     3244
4     2557
5     1473
6      718
10     214
7      188
8      162
Name: time_spend_company, dtype: int64

In [19]:
dataset['promotion_last_5years'].value_counts()

0    14680
1      319
Name: promotion_last_5years, dtype: int64

In [21]:
dataset.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [22]:
dataset['left'].value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [26]:
print(X)

[[0.38 3 0 'low']
 [0.8 6 0 'medium']
 [0.11 4 0 'medium']
 ...
 [0.37 3 0 'low']
 [0.11 4 0 'low']
 [0.37 3 0 'low']]


In [27]:
print(Y)

[1 1 1 ... 1 1 1]


# Encoding Categorical Variables

### Encoding Independent Variable 

In [28]:
#Salary Variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encode',OneHotEncoder(),[3])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [29]:
print(X)

[[0.0 1.0 0.0 0.38 3 0]
 [0.0 0.0 1.0 0.8 6 0]
 [0.0 0.0 1.0 0.11 4 0]
 ...
 [0.0 1.0 0.0 0.37 3 0]
 [0.0 1.0 0.0 0.11 4 0]
 [0.0 1.0 0.0 0.37 3 0]]


# Train and Test split

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

# Feature Scaling

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,4:5] = sc.fit_transform(X_train[:,4:5])
X_test[:,4:5] = sc.transform(X_test[:,4:5])

In [33]:
print(X_train)

[[0.0 0.0 1.0 0.75 1.0333790581525808 0]
 [0.0 0.0 1.0 0.13 1.0333790581525808 0]
 [0.0 1.0 0.0 0.67 -0.3417474050583337 0]
 ...
 [0.0 0.0 1.0 0.69 -1.0293106366637907 0]
 [1.0 0.0 0.0 0.78 -0.3417474050583337 0]
 [0.0 1.0 0.0 0.56 -1.0293106366637907 0]]


# Model 1 (Logistic Regression)

In [35]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [36]:
y_pred = classifier.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(Y_test,y_pred)
print(cm)
accuracy_score(Y_test,y_pred)

[[2123  176]
 [ 518  183]]


0.7686666666666667

# Model 2 (Support Vector Machine)

In [38]:
from sklearn.svm import SVC
classifier1 = SVC(kernel='linear',random_state=0)
classifier1.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [39]:
y_pred1=classifier1.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(Y_test,y_pred1)
print(cm)
accuracy_score(Y_test,y_pred1)

[[2299    0]
 [ 701    0]]


0.7663333333333333

# Model 3 (Kernel SVM)

In [42]:
from sklearn.svm import SVC
classifier2 = SVC(kernel='rbf',random_state=0)
classifier2.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [43]:
y_pred2 = classifier2.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(Y_test,y_pred2)
print(cm)
accuracy_score(Y_test,y_pred2)

[[2115  184]
 [  99  602]]


0.9056666666666666

# Model 4 (K Nearest Neighbour)

In [45]:
from sklearn.neighbors import KNeighborsClassifier
classifier3 = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier3.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [46]:
y_pred3 = classifier3.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(Y_test,y_pred3)
print(cm)
accuracy_score(Y_test,y_pred3)

[[2229   70]
 [  74  627]]


0.952

# Method 5 (Naive Bayes)

In [49]:
from sklearn.naive_bayes import GaussianNB
classifier4 = GaussianNB()
classifier4.fit(X_train,Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [50]:
y_pred4 = classifier4.predict(X_test)

In [51]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(Y_test,y_pred4)
print(cm)
accuracy_score(Y_test,y_pred4)

[[1618  681]
 [ 120  581]]


0.733

#  **Model 6 (Decision Tree Classifier)** 

In [52]:
#Decision Tree Classifier is the winner with 95.86%
from sklearn.tree import DecisionTreeClassifier
classifier5 = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier5.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [53]:
y_pred5 = classifier5.predict(X_test)

In [54]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(Y_test,y_pred5)
print(cm)
accuracy_score(Y_test,y_pred5)

[[2235   64]
 [  60  641]]


0.9586666666666667

# Model 7 (Random Forest Classifier)

In [55]:
from sklearn.ensemble import RandomForestClassifier
classifier6 = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
classifier6.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [56]:
y_pred6 = classifier6.predict(X_test)

In [57]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(Y_test,y_pred6)
print(cm)
accuracy_score(Y_test,y_pred6)

[[2229   70]
 [  55  646]]


0.9583333333333334